---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-sealed
  namespace: tunnels
spec:
  encryptedData:
    credentials.json: AgA6r/ZpjZguNpi/0l8C7afOU4CC39nkdAEKcFtTOazXZI8HtzPhporDdeGlfa50w1xsW2ViS9NxcZwLtRGD1rGVfe3tLSfO7+3zELxYi75ZV9RNHbRUpPhEvJf8WjR9CHGMkuV1QmziJrx8FSTRjNrBg6t7WN39IGlgBq6xEt9iRBI3PYnLP43BCPPxMGMxRwyt/YGGms9rWstTEPIw5jfqjeA3LZJrfRrYGoC/qt9saLrO+EurJbiOHopi0DqWK9d+M97yarZvbNrfZ2+vY0AsJHl5eQMXzM1hSB7kRy9XOLeyUpqf+FfY/5SG5wAdYd8IINtYG6BR/hq3p+nLhlXoewryOBW4MWw9Ro0LWianRIzJw3X37qU0j6BwlekDOsZ+mYeM5WmGd0NSdQrv2PKghk1wmSBeBZ9G+Jne/FJR2tsAJOs5ltJoGGn8SfiUw08KqPhHyPdPr6ynR8wmCvxxtk+3c4cf1UqRjekdtRLfsze2dE6SiQxjVeTrLBz48aA1f4mIipTc5V1TVp7TDiAlTs/y64dybEHkd8SDKTOO5wwCS2bkbfy1gvBBLqyMg4mBFTVZ2NBheUi+DDbRyW2IO6GVcBQxGY3jRtzJlxrGJ6Yt+Wz5UJ04yDj03xVH0DWlhAfDCA5A/fa8QIfGbvj6ke9MgyZPy7vucGV1NYhtkq0wLMOpQaWz7QceMQ6FdAwYaorjqGzJ2saOXbsPpk1FhzMzmHIOE5ln3bo3m3KaLgDAYI0YrvAFMJ8CqMnKMkRMY5f4RED/VK3TgmzSLHbPd4TRMDmZBgYrPC2Xh33PxXT3O7ePaAcdn/NTS6IBB76/JUQw+UI+NmqfjLv3nbBs8018e08bX+/g/QcuadA8b7V7JcIAKTWZ5LzGKXDBmkZ4d7QtIL150E3lBGTXeeSxgQJTcf4pnFCSy8d2qJkfe48R1mlxSKmUk8OZrDm1Fojrq4Fw6TUVC7lVfdIDdqhHZRSOIjiB0jrSNToqNXasSzcVNuwb1MU1MQFf8VH6+HkGE38rdJepvi484q8qdOgVTLXhP8Hr0VScK7N0NA==
  template:
    metadata:
      name: cloudflare-tunnel-sealed
      namespace: tunnels
