---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-sealed
  namespace: tunnels
spec:
  encryptedData:
    credentials.json: AgBF7LWUfH5+vJqnA0GUhNEc0aCXZmS61E2hVgYgVG949y1jTP0NOvq/0NteR5BM1V4eWcmWFtNGh0YVNcrNnFK1eRSynkzdEPr2XaEfEdl8aT2rLnJIT6LuFBC2oK2DuCN0RGgEx9cEQasKIMUzlY+XQNYclH/3Yvuw8gPCkskVkA79JigrwCBMG+wDXB04uOOJLAxIsfGDlutyFstzO50TCPZlWogRzccLqUCWKrZ2ml+bv+zCPtPI8x+7lm1e9mlMBFZrYxre4WWU7ZPxflrmM07wr0rrm7C5RBB2OSTezp+I3rV5MzdfY+J6u8c47VPtJgLf9fXCxQ45TjuN94n9QSTnyH2ODVyD1vrraAct62IMcDowIDKhF2W6P0px9Qj1rqy3niOHXPfxL3k/qSDZM37ZWnvAnoja85AuA62De+OOX/1YbKLv/oRJeUo/SpdiLmI+VQ9LG97djLpXqxEIIp/k9VMV2mxUC8f0DxElDTtoU/71F3JkHwoCSvczaiRbWajFcoml39C4mWkP4i5FqYIJ2ZxL5kz8+J/qE17FaNSnSiVlIYfTLIpYN9r70OzMVruqvynMklcNIefjY/+cO/hKt4Vevc5lJLvcMPS6gmTbhzH4gZZGNJKrQe/3oWXmQ+ZWHM5Mi7W0QbwK5OUg7m6P4Ta+MlRJ4qBlUoSGt5OQ4v3hbU4+nXUJKTnlEQOeal4vd99ejFKRyp6EYvvsRhhoXpkI2zmngNqMJdHcAYMXoAJ8OIggHIzC0NQ2n+6aQz+nGIhROX/cjMgTlG6ozFtmIUEH6igpRcEOS30Q2RRFzYiewyodHhFW2ZuecRdXYLsTaMqnIHJsBGNAQ8ebtjcoOzwfyffftBZtH+CrHMy0PODf7G8XcdE/a7yd+gYwh+MQmwGNVZ/aCBSmtUNeMEyakJcU9f4BSfQDO5cSRQ==
  template:
    metadata:
      name: cloudflare-tunnel-sealed
      namespace: tunnels
