{{- if and .Values.publicTunnel.enabled (not .Values.publicTunnel.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-public-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudflared-public
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "",
      "TunnelSecret": "{{ .Values.publicTunnel.tunnelToken }}",
      "TunnelID": "{{ .Values.publicTunnel.tunnelId }}"
    }
{{- end }}
