apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            {{- range .Values.backend.volumes.pvc }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.backend.env | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.backend.volumes.pvc }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            - name: youtube-patch
              mountPath: /app/packages/backend/dist/voice/audio/youtube.js
              subPath: youtube.js
      volumes:
        {{- range .Values.backend.volumes.pvc }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" $ }}-{{ .name }}
        {{- end }}
        - name: youtube-patch
          configMap:
            name: {{ include "common.fullname" . }}-youtube-patch
