apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-sidecar
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: sidecar
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sidecar.service.port }}
      targetPort: {{ .Values.sidecar.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sidecar
