---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-api-key
  namespace: media
spec:
  encryptedData:
    api-key: AgBts8ru9ZxnpmAhp0joyEBMYvW8hm9inklCzNpKiK5/59yOMK3M1a78pVa96ZFcuV4r0Tcdvsxs6YFR+JvPcwKa+P+bzHRynU8M0lYvXbNwge2Ufc/W6J46BO1tLJ30Gis/DgVqDBpPWsGALEglW+weo3BUEikAWwxw+mKunBUJvaL9e3eVESGNckH8hYvmta0+2q6htg+/4xo1PwnFcAHixYdpDJzWaAkLyofPbYA5GPiKtwUvUp6clEYgQZkN+uiWk7q1M2BAWQwce7lzIV3G42m24mqgbixRpwp/rO3jdIA7ZYSOPh+vp7IcWLudbnhYGmaT/SAJ5FB0uhnQbimzqKyCiJou3+U4XF5p2qvqHdSAXgC4goLwQIPe2mI1TsOLzafb7FUwF4+CZaYD0NKe7DYBoxW+0RXk4crHTy1BBYX5/M7D3dMxzokPuk3UFleW+ZfRCNNy6z2Evwkrjr70TMusQCGY6CR89DYK/pJSaoO8YkA1v1rMWnDOMn3jIBGd9OZyFtFPn8YqJaAFJ1J8LPqBK7SJ4CMBPiM0bLl6wXOXodZECfcXD9AMLn5gfF4sxRXczNQmFVIlTFi7typgnZIK3gz6mNgr+Vcb1FDRDo6twVTQT5Dubdhev0sJRr/GVwzqh00y5/Oze6kC+/DCnazRNd46AVM69LfYsJoo9y635eohgraxbGeH3+5HKsG+GBChLJ4oqNjkK1MM+TbxSEjT9W2Kid8LM+j1Lkp5IQ==
  template:
    metadata:
      name: sonarr-api-key
      namespace: media
