apiVersion: v2
name: prowlarr
description: Prowlarr indexer manager for *arr stack
type: application
version: 1.0.0
appVersion: "2.3.0"
keywords:
  - prowlarr
  - indexer
  - media
home: https://prowlarr.com
maintainers:
  - name: andrewzn69
dependencies:
  - name: common
    version: 3.0.10
    repository: oci://ghcr.io/andrewzn69
