namespace: media

image:
  repository: ghcr.io/home-operations/prowlarr
  tag: "2.3.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9696
  targetPort: 9696
  protocol: TCP
  name: http

gateway:
  enabled: true
  gatewayName: internal
  gatewayNamespace: gateway-system
  hostname: prowlarr.internal.zemn.xyz
  path: /
  pathType: PathPrefix

volumes:
  pvc:
    - name: config
      mountPath: /config
      size: 5Gi
      accessMode: ReadWriteMany
      storageClassName: longhorn

resources:
  requests:
    memory: 256Mi
    cpu: 25m
  limits:
    memory: 512Mi
    cpu: 200m

env:
  - name: PUID
    value: "10001"
  - name: PGID
    value: "10001"
  - name: TZ
    value: "Europe/Prague"

replicaCount: 1

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

configMap:
  enabled: false

initContainers:
  fixPermissions:
    enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

metrics:
  enabled: false
