namespace: media

image:
  repository: docker.io/jellyfin/jellyfin
  tag: latest

storage:
  configSize: 1Gi
  cacheSize: 1Gi
  storageClass: nfs-storage

nfs:
  server: 192.168.0.113
  paths:
    config: /mnt/external/config/jellyfin/config
    cache: /mnt/external/config/jellyfin/cache
    shows: /mnt/external/Shows
    movies1: /mnt/movies1/Movies
    movies2: /mnt/movies2/Movies

ingress:
  host: jellyfin.zemn.xyz
  tlsSecretName: zemn-wildcard-tls
