apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-webquery
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 10080
      targetPort: 10080
      protocol: TCP
      name: webquery
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
