# chart metadata
nameOverride: ""
fullnameOverride: ""

# kubernetes namespace
namespace: media

# container image configuration
image:
  repository: docker.io/jellyfin/jellyfin
  tag: "10.10.7"
  pullPolicy: IfNotPresent

# service config
service:
  type: ClusterIP
  port: 8096
  targetPort: 8096

# volume config
volumes:
  mounts:
    - name: jellyfin-config
      mountPath: /config
      type: pvc
      readOnly: false
      pvc:
        nfsServer: "100.64.100.64"
        nfsPath: "/storage/apps/jellyfin/config"
        size: 10Gi
        accessMode: ReadWriteMany
    - name: jellyfin-cache
      mountPath: /cache
      type: pvc
      readOnly: false
      pvc:
        nfsServer: "100.64.100.64"
        nfsPath: "/storage/apps/jellyfin/cache"
        size: 50Gi
        accessMode: ReadWriteMany
    - name: jellyfin-shows
      mountPath: /media/Shows
      type: pvc
      readOnly: true
      pvc:
        nfsServer: "100.64.100.64"
        nfsPath: "/storage/media/shows"
        size: 1Ti
        accessMode: ReadOnlyMany
    - name: jellyfin-movies
      mountPath: /media/Movies
      type: pvc
      readOnly: true
      pvc:
        nfsServer: "100.64.100.64"
        nfsPath: "/storage/media/movies"
        size: 1Ti
        accessMode: ReadOnlyMany

# ingress config (disabled because using direct cf tunnel)
ingress:
  enabled: false
  className: nginx
  host: jellyfin.zemn.xyz
  tlsSecretName: zemn-wildcard-tls

# resource limits/requests
resources:
  requests:
    memory: "1Gi"
    cpu: "1000m"
  limits:
    memory: "4Gi"
    cpu: "4000m"

# security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
