{{- if .Values.cloudflared.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cloudflared
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cloudflared
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cloudflared
    spec:
      containers:
      - name: cloudflared
        image: {{ .Values.cloudflared.image }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        args:
        - tunnel
        - --config
        - /cloudflared/config.yaml
        - --no-autoupdate
        - run
        - {{ .Values.cloudflared.tunnelId }}
        volumeMounts:
        - name: config
          mountPath: /cloudflared/config.yaml
          subPath: config.yaml
        - name: secrets
          mountPath: /cloudflared/tunnel-credentials.json
          subPath: tunnel-credentials.json
        - name: secrets
          mountPath: /cloudflared/cert.pem
          subPath: cert.pem
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-cloudflared-config
      - name: secrets
        secret:
          secretName: {{ .Release.Name }}-cloudflared-secrets
{{- end}}
