apiVersion: v2
name: seerr
description: Seerr media request management
type: application
version: 1.0.0
appVersion: "v3.1.0"
maintainers:
  - name: andrewzn69
dependencies:
  - name: common
    version: 3.0.7
    repository: oci://ghcr.io/andrewzn69
