namespace: media

image:
  repository: ghcr.io/seerr-team/seerr
  tag: "v3.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5055
  targetPort: 5055
  protocol: TCP
  name: http

cloudflare:
  enabled: true
  hostname: seerr.zemn.xyz
  path: /
  pathType: Prefix

volumes:
  pvc:
    - name: config
      mountPath: /app/config
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClassName: local-path

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFileSystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 512Mi
    cpu: 500m

env:
  - name: TZ
    value: "Europe/Prague"

replicaCount: 1

configMap:
  enabled: false

initContainers:
  fixPermissions:
    enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

metrics:
  enabled: false
