cert-manager:
  crds:
    enabled: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

  webhook:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  cainjector:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

infisical:
  enabled: true
  hostAPI: https://eu.infisical.com
  projectId: "481ebc3e-b9ed-40e7-9417-07aafe84aad1"
  envSlug: prod
  secretsPath: "/infrastructure/cert-manager"
  resyncInterval: 60
  credentialsSecret:
    name: infisical-universal-auth
    namespace: infisical-system

clusterIssuer:
  name: letsencrypt-cloudflare
  email: ondrejzeman23@gmail.com
  cloudflare:
    tokenSecretName: cert-manager-cloudflare-dns-token
  dnsZones:
    - "zemn.xyz"

certificate:
  name: zemn-wildcard
  secretName: zemn-wildcard-tls
  dnsNames:
    - "zemn.xyz"
    - "*.zemn.xyz"
    - "*.internal.zemn.xyz"

gateway:
  namespace: kube-system
