
image:
  repository: itzg/minecraft-server
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: ""

replicaCount: 1

resources:
  requests:
    cpu: 2300m
    memory: 16Gi
  limits:
    cpu: 2300m
    memory: 16Gi

lifecycle:
  postStart: []
  preStop: []

workloadAsStatefulSet: false

strategyType: Recreate

nodeSelector:
  kubernetes.io/hostname: "worker-1"

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  runAsNonRoot: true
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

livenessProbe:
  command:
    - mc-health
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  command:
    - mc-health
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1
startupProbe:
  command:
    - mc-health
  enabled: false
  failureThreshold: 30
  periodSeconds: 10

minecraftServer:
  eula: "TRUE"
  version: "LATEST"
  # This can be one of "VANILLA", "FORGE", "SPIGOT", "BUKKIT", "PAPER", "FTBA", "SPONGEVANILLA", "AUTO_CURSEFORGE"
  type: "VANILLA"
  difficulty: easy
  maxPlayers: 20
  allowNether: default
  announcePlayerAchievements: default
  enableCommandBlock: default
  forcegameMode: default
  generateStructures: default
  hardcore: default
  maxBuildHeight: 400
  maxTickTime: 60000
  spawnAnimals: default
  spawnMonsters: default
  spawnNPCs: default
  spawnProtection: 0
  viewDistance: 10
  gameMode: survival
  motd: "Total nigger death"
  pvp: default
  levelType: DEFAULT
  worldSaveName: world
  forceReDownload: false
  removeOldMods: false
  resourcePackEnforce: false
  onlineMode: default
  enforceSecureProfile: default
  memory: 15000M
  overrideServerProperties: false
  serviceType: NodePort
  servicePort: 25565

  autoCurseForge:
    apiKey:
      key: "$$2a$$10$$uuUcUzCrKd.7H5TYMQ1OR.b8sJnrcgpk9OAJ1EdSGaDbr68m6pG.u"
      existingSecret: ""
      secretKey: cf-api-key
    pageUrl: "https://www.curseforge.com/minecraft/modpacks/ftb-stoneblock-3"
    slug: ""
    fileId: "5813067"
    filenameMatcher: ""
    excludeMods: []
    includeMods: []
    excludeIncludeFile: null
    forceSynchronize: false
    setLevelFrom: ""
    parallelDownloads: 4
    overridesSkipExisting: false

  rcon:
    enabled: false
    withGeneratedPassword: false
    port: 25575
    password: "nepamatujusiheslo"
    existingSecret:
    secretKey: rcon-password
    serviceType: NodePort
    nodePort:
    clusterIP:
    loadBalancerClass:
    loadBalancerIP:

  query:
    enabled: false
    port: 25565

persistence:
  labels: {}
  annotations: {}
  dataDir:
    enabled: true
    Size: 30Gi
    accessModes:
      - ReadWriteOnce


volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true


tolerations: []

affinity: {}

initContainers:
  - name: fix-permissions
    image: busybox
    command: ['sh', '-c', 'chmod 777 /data && chown -R 1000:3000 /data']
    volumeMounts:
    - name: datadir
      mountPath: /data
    securityContext:
      runAsUser: 0
      runAsNonRoot: false

sidecarContainers: []

extraVolumes: []

extraDeploy: []

extraPodSpec:
  hostNetwork: "true"
  dnsPolicy: "ClusterFirstWithHostNet"

envFrom: []

mcbackup:
  enabled: false

  image:
    repository: itzg/mc-backup
    tag: latest
    pullPolicy: IfNotPresent

  #  wait 2 minutes before starting
  initialDelay: 2m

  # ***set to 0 or smaller, script will run once and exit.  DO NOT SET TO 0 or smaller, this will cause K8s to kill your pod!***
  # backupInterval="1.5d" -> backup every one and a half days (36 hours)
  # backupInterval="2h 30m" -> backup every two and a half hours
  backupInterval: 24h

  # option lets you pause backups if no players are online.
  pauseIfNoPlayers: "false"

  # is set to a positive number, it'll delete old .tgz backup files from DEST_DIR. By default deletes backups older than a week.
  pruneBackupsDays: 7

  # Set to a negative value to retry indefinitely
  rconRetries: 5
  rconRetryInterval: 10s

  # is a comma-separated list of glob(3) patterns to exclude from backups. By default excludes all jar files (plugins, server files),
  # logs folder and cache (used by i.e. PaperMC server).
  excludes: "*.jar,cache,logs"

  # backup methods, see https://github.com/itzg/docker-mc-backup e.g. tar, rclone, restic, rsync
  backupMethod: tar
  # tar and rclone methods
  destDir: /backups
  # is a true/false flag that creates a symbolic link to the latest backup
  linkLatest: "false"
  # is the compression method used by tar. Valid value: gzip bzip2 zstd
  compressMethod: "gzip"
  # sets the parameters for zstd compression. The --long parameter affects RAM requirements for both compression and decompression
  # (the default of 25 means 2^25 bytes = 32 MB).
  zstdParameters: "-3 --long=25 --single-thread"
  # the name of the remote you've configured in your rclone.conf
  rcloneRemote:
  rcloneDestDir:
  rcloneCompressMethod: gzip

  # see https://rclone.org/ for details
  # this value is evaluated as a template
  rcloneConfig:
  # [remote]
  # type = google cloud storage
  # client_id =
  # client_secret =
  # token = {"AccessToken":"super","RefreshToken":"secret","Expiry":"date","Extra":null}
  # project_number = 12345678
  # object_acl = private
  # bucket_acl = private

  # if you prefer to create a secret from file (e.g. kubectl create secret generic my-rclone-config --from-file=~/.config/rclone/rclone.conf)
  # rcloneConfigExistingSecret: my-rclone-config

  resticRepository: ""
  # variable to define a space separated list of additional restic tags. see https://hub.docker.com/r/itzg/mc-backup
  resticAdditionalTags: "mc_backups"
  # see https://restic.readthedocs.io/en/latest/060_forget.html
  pruneResticRetention: "--keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75"

  # At least one of RESTIC_PASSWORD* env variables need to be defined, see https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html
  resticEnvs:
    {}
    # RESTIC_PASSWORD: restic-password

  ## Additional minecraft container environment variables
  ## Values can be either variable values or `valueFrom` yaml
  ##
  extraEnv:
    {}
    # some_variable: some value
    # another_variable:
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: status.hostIP

  ## Additional environment variables to add to the mc-backup container from
  ## ConfigMaps and Secrets
  ##
  envFrom: []

  resources:
    requests:
      memory: 4Gi
      cpu: 2

  persistence:
    annotations: {}
    ## minecraft data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    backupDir:
      # Set this to false if you don't care to persist state between restarts.
      enabled: false
      # existingClaim: nil
      Size: 1Gi
      accessModes:
        - ReadWriteOnce
