apiVersion: v2
name: radarr
description: Radar movie manager for *arr stack
type: application
version: 1.0.0
appVersion: "5.28.0"
keywords:
  - radarr
  - movies
  - media
home: https://radarr.video
maintainers:
  - name: andrewzn69
