apiVersion: v2
name: radarr
description: Radar movie manager for *arr stack
type: application
version: 1.0.0
appVersion: "6.0.4"
keywords:
  - radarr
  - movies
  - media
home: https://radarr.video
maintainers:
  - name: andrewzn69
dependencies:
  - name: common
    version: 1.0.10
    repository: oci://ghcr.io/andrewzn69
