namespace: media

image:
  repository: ghcr.io/home-operations/radarr
  tag: "6.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7878
  targetPort: 7878
  protocol: TCP
  name: http

gateway:
  enabled: true
  gatewayName: internal
  gatewayNamespace: kube-system
  hostname: radarr.internal.zemn.xyz
  path: /
  pathType: PathPrefix

volumes:
  pvc:
    - name: config
      mountPath: /config
      size: 5Gi
      readOnly: false
      accessMode: ReadWriteOnce
      storageClassName: longhorn

  nfs:
    - name: movies
      mountPath: /movies
      server: "100.64.100.64"
      path: "/storage/media/movies"
      readOnly: false
    - name: downloads
      mountPath: /downloads
      server: "100.64.100.64"
      path: "/storage/downloads"
      readOnly: false

resources:
  requests:
    memory: 256Mi
    cpu: 25m
  limits:
    memory: 512Mi
    cpu: 200m

replicaCount: 1

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

configMap:
  enabled: false

initContainers:
  fixPermissions:
    enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

metrics:
  enabled: false
