---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCxRjkP9EzQBSe0cg0iM1AnjTFo+SI8Igj3z5r8DmjNBNeEG8a3a9HP0QMqNQKacoGzpJEzMO6umnbaVWgZBDbPyOJ+Bfsol91nU/XpeeiuTlHLE/IovXLm0+j/LBLTLmp7efI9I5usM4E53MMtSuHjiXp0YA+w3dyOJ1cwKUE7faJ79HFDX1wJ5tijR8E28SeytmnGRJQ9u6HuAe9vvZD3ZyzbMT03UI5X5C3GcYKC7b5SBeXKJkgkDdCkOjO/dNxeKENjcvuoqdZNG7V2zTQ17nYbMGvfk5DqTWMXoUaM4rBaaJOeVAYxzSgjRKwYs9oPld0vFE/BGG+nmCOMFFpZipxrNVtiEEm5frosoMz3Xr6LSeUGPo2kpUZ+wLfGk0HQfDXqWcpM7+IRQJdEKp1gCuUM3pVKLVm6VY1QsITK7ObJ8COPWrLTw1vMh2/dP0hrvH2gXS8powvTqj/WFZeAuejEKAEG0CVdb+A8WsbJYd/j21+UnHulGDFWm4Oe/K21vlJGw4GrCwx73UQU4DfhzNSsY5JX3j2CCFWnaz1QIp+3j1IEKNx8SzKyshr91BnQORPgXe8Ju0HvUDaqN83jtPBEHpgN3fbv8oHrB9cX47ZN+nodxKKQWsISGoU86Z/rHu3j7Oc/OzIV4H816kQ35hk0ozZZFAWS8On9nsPS8qwz1ewH5M8lMMLb2HxUQRkYhX7yvK8eULhfi6Xifeu1cogO+RVe15bkuNRyAarCU8T1Ukec
    admin-user: AgAK02TCnv4slZE7S+QkPNysm9D323fSUo67l2eAxXpjNz1/3245QViQaMvJpDFBUHRiKHfNVtj4EOa7DVWS2DNoF1T2V5QdladdHKFUQVgtHjfW+A37L+9xqA0QvH9bV0eU31P5SdlK+lmAZmZS9/vKPTvt6ngzH87xI1RBWdz+9clLMsVHhy/3txfNWdv0dqp8H55le6ka4irI5I6lxGNOWLjJdgG+jGWpD0cKPhsr09egqe3H3NVv2L+3yuMMeUl5R0uxXQbbdHkLWMlE5WyfotcHJDt7HYwPsqXQwR0cSkgp+znIHG5pCgnqQnQo4w6WKYkGuh6gUdZs6aJtJpZwv6KCLAVqO+eeT79Khoq99E6WG+YRmpZ4TyXjh2tXsKkmyKj19tBx2QUKuLs7Ewv0AaYWJXnwK2q4wR3tj1Wn9lnwqMQ4PCcZOoOg0f5Aw1AM/kMO8TgcTSWvITdH3O5FJbtFO1IL6gWylzbLNFpZoKvOLtRWhUTb28VIycnAC8jxwJN0+cZv6Vdnodiz7jaDAUbhR+G0IJcBYvFDyxep7ZnXRKpKShUEDkmRFeYKIYLJzwy2opLS0KnIrpWWVL2xYHcYKrIVJrw2tO4WpQXOPt9lsLIig2yhI36dEXw/BkUTsjhwcr2gtProTanuQ27H/WbBENFAnf73G5QdfL78x+V+fOCpqoW986OiWXvpcLbT++vbYXNRCd4DEawJ
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: Opaque
