apiVersion: v2
name: cloudflare-tunnel-controller
description: Cloudflare Tunnel Ingress Controller
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 3.0.8
    repository: oci://ghcr.io/andrewzn69
  - name: cloudflare-tunnel-ingress-controller
    version: 0.0.23
    repository: https://helm.strrl.dev
