namespace: cloudflare-tunnel-controller

# override fullname to match expected secret name
fullnameOverride: cloudflare-api

# secret config
secrets:
  enabled: true
  type: infisical
  infisical:
    hostAPI: https://eu.infisical.com
    projectSlug: novigrad
    envSlug: prod
    secretsPath: /infrastructure/cloudflare
    auth:
      credentialsSecretName: infisical-universal-auth
      credentialsSecretNamespace: infisical-system
    managedSecret:
      creationPolicy: Owner

# cloudflare tunnel controller config
cloudflare-tunnel-ingress-controller:
  cloudflare:
    secret: cloudflare-tunnel-controller
    tunnelName: novigrad-tunnel
  cloudflared:
    image:
      repository: docker.io/cloudflare/cloudflared
      tag: latest
