publicTunnel:
  enabled: true
  useExistingSecret: true
  existingSecretName: cloudflare-tunnel-sealed
  tunnelId: "a62edbf3-830c-4ecb-ad45-4b82ab497141"
  image: cloudflare/cloudflared:2025.8.1
  services:
    - hostname: jellyfin.zemn.xyz
      service: http://jellyfin.media.svc.cluster.local:8096
    - hostname: jellyseerr.zemn.xyz
      service: http://jellyseerr.media.svc.cluster.local:5055
