apiVersion: v2
name: qbittorrent
description: qBittorrent torrent client
type: application
version: 1.0.1
appVersion: "5.1.4"
keywords:
  - qbittorrent
  - torrent
  - download
home: https://www.qbittorrent.org
maintainers:
  - name: andrewzn69
dependencies:
  - name: common
    version: 1.0.6
    repository: oci://ghcr.io/andrewzn69
