namespace: media

components:
  qbittorrent:
    image:
      repository: ghcr.io/home-operations/qbittorrent
      tag: "5.1.4"
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 8080
      targetPort: 8080
      protocol: TCP
      name: http

    gateway:
      enabled: true
      gatewayName: internal
      gatewayNamespace: gateway-system
      hostname: qbittorrent.internal.zemn.xyz
      paths:
        - path: /
          pathType: PathPrefix

    volumes:
      pvc:
        - name: config
          mountPath: /config
          size: 10Gi
          accessMode: ReadWriteOnce
          storageClassName: longhorn
      nfs:
        - name: downloads
          mountPath: /downloads
          server: "100.64.100.64"
          path: "/storage/downloads"
          readOnly: false

    resources:
      requests:
        memory: 192Mi
        cpu: 25m
      limits:
        memory: 256Mi
        cpu: 200m

    env:
      - name: TZ
        value: "Europe/Prague"
      - name: WEBUI_PORT
        value: "8080"

    replicaCount: 1

    securityContext:
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    configMap:
      enabled: false

    initContainers:
      fixPermissions:
        enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    metrics:
      enabled: false
