nameOverride: ""
fullnameOverride: ""

namespace: media

image:
  repository: docker.io/linuxserver/qbittorrent
  tag: "5.1.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

volumes:
  mounts:
    - name: qbittorrent-config
      mountPath: /config
      type: pvc
      readOnly: false
      pvc:
        nfsServer: "100.64.100.64"
        nfsPath: "/storage/apps/qbittorrent"
        size: 10Gi
        accessMode: ReadWriteMany
    - name: qbittorrent-downloads
      mountPath: /downloads
      type: pvc
      readOnly: false
      pvc:
        nfsServer: "100.64.100.64"
        nfsPath: "/storage/downloads"
        size: 500Gi
        accessMode: ReadWriteMany

ingress:
  enabled: true
  className: nginx
  host: qbittorrent.zemn.xyz
  tlsSecretName: zemn-wildcard-tls
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

resources:
  requests:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 2Gi
    cpu: 2000m

env:
  - name: PUID
    value: "1000"
  - name: "PGID"
    value: "1000"
  - name: TZ
    value: "Europe/Prague"
  - name: WEBUI_PORT
    value: "8080"
