# infisical config
infisical:
  enabled: true
  hostAPI: https://eu.infisical.com
  projectId: ""
  envSlug: prod
  secretsPath: "/infrastructure/tailscale"
  resyncInterval: 60
  credentialsSecret:
    name: infisical-universal-auth
    namespace: infisical-system

# tailscale connector config
connector:
  enabled: true
  name: subnet-router
  exitNode: true
  tags:
    - tag:k8s-operator
  subnetRouter:
    enabled: true
    advertiseRoutes:
      - "10.244.0.0/16" # pod network
      - "10.96.0.0/12" # service network

# tailscale operator config
tailscale-operator:
  oauth:
    secretName: tailscale-oauth
  operatorConfig:
    hostname: "vizima-k8s-operator"
