{{- if .Values.exportarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "radarr.fullname" . }}-exportarr
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "radarr.fullname" . }}-exportarr
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.exportarr.port }}
      targetPort: {{ .Values.exportarr.port }}
      name: metrics
  selector:
    app: {{ include "radarr.fullname" . }}-exportarr
{{- end }}
