---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-api-key
  namespace: media
spec:
  encryptedData:
    api-key: AgAJht8wtbetr4eoswCjKgi/R77xUnl3wv3TcO7Qv1cSpyXGhzJ2hL3kGmSRuQ9mApO9zQA3OZzJufBBuhk9fMY9mSyvn5Dm13R9pLHCthOiOH1g8sUiDzdJsH7jyv2zv4HkqmyEfCP4zdUo6TguULktTtI9MgY059nGIk9Y5xHz4uuL5Q7O3GLFiGYvfwNixBRhoPOR5ytvFDAkfhFzr647we7eLvVc4Ts6wZoyK/eK5Au6n/XzIBPXmBuzKktnJtz6DlKrW/GHw51AHbHUL5tPZ2tbCTBvlxHBZ3Pug/yKyXxCDH+CcSx3DPKHy8l96EGwa6owB8+z2OQnrROwTgKQDk06qfp+IGtbmbVBKXtATRWFvbFJPVq1Ah6G+ZDxZSf21rnbKjQLtWKfnKEnd0/OyKEeugFnT+bKwCDIj680L1BfsxtI5LK+clV3kacg7ebSlu/ghbcERM+iv4jTzt4tNyFdnUv7brmncOnB2tC6wWrRGervPp7BnrlKBirTWxx/1P/IotfmR/Mcp+DuAGwZaND3BRIPvp7lIhoN4YoNZ35LiSr8KXlNNVgAEMD8GeNQOVC4ESIuCRznaMbFeNb34/UHBVLTc7ClYQOnbC9dcJGE9MbpwYem2hfG16Ve32rwbate426O9EKAvimsBk1MBvKw4Jg63fmW5B6kX3Tdfhhr/HN4RcvJ/o65z61+5+sUdYV7Gh3cCO587aZS7h2LseuCEYKLaIJiMCTxPEuwpQ==
  template:
    metadata:
      name: radarr-api-key
      namespace: media
