apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jellyfin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        fsGroup: {{ .fsGroup }}
        fsGroupChangePolicy: "OnRootMismatch"
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8096
          protocol: TCP
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- range .Values.volumes.mounts }}
        - mountPath: {{ .mountPath }}
          name: {{ .name }}
          {{- if .readOnly }}
          readOnly: {{ .readOnly }}
          {{- end }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      {{- range .Values.volumes.mounts }}
      - name: {{ .name }}
        {{- if eq .type "nfs" }}
        nfs:
          server: {{ .nfs.server }}
          path: {{ .nfs.path }}
        {{- else if eq .type "pvc" }}
        persistentVolumeClaim:
          claimName: {{ .name }}
        {{- else if eq .type "emptyDir" }}
        emptyDir:
          {{- if .emptyDir.sizeLimit }}
          sizeLimit: {{ .emptyDir.sizeLimit }}
          {{- end }}
        {{- end }}
      {{- end }}
