apiVersion: v2
name: jellyfin
description: Jellyfin media server
type: application
version: 1.0.1
appVersion: "10.11.6"
keywords:
  - jellyfin
  - media
  - streaming
home: https://jellyfin.org
maintainers:
  - name: andrewzn69
dependencies:
  - name: common
    version: 3.0.7
    repository: oci://ghcr.io/andrewzn69
