# kubernetes namespace
namespace: media

# container image configuration
image:
  repository: docker.io/jellyfin/jellyfin
  tag: "10.11.0"
  pullPolicy: IfNotPresent

# service config
service:
  type: ClusterIP
  port: 8096
  targetPort: 8096
  protocol: TCP
  name: http
  nodePort: ""
  loadBalancerIP: ""
  annotations: {}
  additionalPorts: []

# volume config
volumes:
  pvc:
    - name: config
      mountPath: /config
      size: 10Gi
      accessMode: ReadWriteOnce
    - name: cache
      mountPath: /cache
      size: 20Gi
      accessMode: ReadWriteOnce

  nfs:
    - name: movies
      mountPath: /media/Movies
      server: "100.64.100.64"
      path: "/storage/media/movies"
      readOnly: true
    - name: shows
      mountPath: /media/Shows
      server: "100.64.100.64"
      path: "/storage/media/shows"
      readOnly: true

# cf tunnels ingress
cloudflare:
  enabled: false
  hostname: jellyfin.zemn.xyz
  path: /
  pathType: Prefix

# resource limits/requests
resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 3Gi
    cpu: 3000m

# container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

# pod security context
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# replica count
replicaCount: 1

# env variables
env: []

# config map
configMap:
  enabled: false

# secrets
secrets:
  enabled: false

# init containers
initContainers:
  fixPermissions:
    enabled: false

# probes
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

# metrics
metrics:
  enabled: false
  port: 9090
  path: /metrics
  serviceAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
