apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andrewzn69/kubernetes
    targetRevision: HEAD
    path: charts/productivity/linkding
    helm:
      releaseName: linkding
  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
