apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andrewzn69/kubernetes
    targetRevision: HEAD
    path: charts/productivity/plane
    helm:
      releaseName: plane
  destination:
    server: https://130.162.228.5:6443
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
