apiVersion: v1
kind: PersistentVolume
metadata:
  name: terraria-world-data
spec:
  capacity:
    storage: {{ .Values.persistence.worldData.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: {{ .Values.persistence.worldData.nfsServer }}#{{ .Values.persistence.worldData.nfsPath }}#terraria-world-data
    volumeAttributes:
      server: {{ .Values.persistence.worldData.nfsServer | quote }}
      share: {{ .Values.persistence.worldData.nfsPath | quote }}
