apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terraria-password
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    password: AgB/HbFwd0l3zI6+c9qHM+xTk9eFeeLy0Dz5dmISkxKhqfxyvNAT/dgM89UBheudogu1rGwd8W8LIa5zEUa27DQao7H/BkgwmpX4Jcc0yKmYUv0oBQdRuoFjktbXjTVjblOL2ZxOicjlWoepmEpU9zc7yVEyg+3GNZjPC0s42ngk2Oh+QUZ+JAe7OjE+aPtNq84ZV/Sb4SlbVg7Harejv2iLjn62DCzRudp9oH25TinBILSaCEdINq3GB3HJlLHXgmjKE/j0UmWbx+va+WUnfsfiyhnISUjDUll/cbK8IJ16YDiGlLUvt9WZOtHfM1B7geUBFiUWNaZdGjZyg2J9guIi2kZoBnKBU8pcW1T5V+grB498nVJaCAfT2pQmAKOoNGxQANczeZ7Ye8JXsS3rj90vGLHpPlLYFsqjo+J9oSI5Z+rM83sLmhVZ/jzRBRb2cUmkDcSxAV8smy6myLutRz6a28jzS9iupSZ6Yz9sZTElWemEocv8YuxZd5Ibu90CLGtMr0IdpyNzFaOgRJHST/jvsP1H57EKdwY9m+xwGiMDWAuhzJ/4be4jxASOr05JRh8wZew93oXtN+SwLSWoUcHNIdr/vOFc1+UPkq5pbQGjaKUo1OiygBBchn8/4PavLWoUy3IcMATZgJkOuSkhGe9j3JU8G5YBtu/XjP2+WXqhDXMweqLn1sr+zuFGDnpJp2pz+5/35Sw=
  template:
    metadata:
      name: terraria-password
      namespace: {{ .Values.namespace }}
