apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terraria-password
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    password: AgCjbaR+Ts+YMRVJoRS6ONkJ5YT2QLmueldl/0p3mzc6u75Vm12dXnAFZspKc9JsNPDPMeW3yA8QFBcHby9rUt6PyZWDo9gnMInvCx1cNEwnoUBYrDJzz3dsWvDwQbNxATklTy0aAf5c41dgsyaDunkNUFxjyKX+ZGyhkZH4QiUUOuPe5fwUtIKhV8+1aKfAZQuxTyJpEt3y0e+SWIvazZMCdaPwZKmoBLAwDGBPx/xxWjv0Xax8mwW8CEiJpmIH06fwxM6P/R6RXbCA0khd0IdkY3xEamtK0SrjwntTZr8AuMJBAJxt91AO/8cxyUjvZ7RYL+zNKqmBwlp5LoVlkLSipMnpp7V64Ubx7ZSOsudG/Lop4UVZUwJcdpsoYtmv3aWwdg1Xvmi+prmmM3OMBVCoDkXAodBihy3b90aKZPXss6nVidZQ9g6BQlln9FIyxCae35nvqtKrqAotouHIcr5Gmyw1Kmwecanci7UBWQBRiGHtX3Go1dw9yRC4Z5CqrRLGns9HJ+h0StRohHaMVCJHZQSMUOIdKWoXSn19i+2vDuDIBLis0BoXsFNV10cFZC07sb88aH5Ly6QQTdVsZllQACXE8dcHfqhglR26A2Tx2gbtu6eIJzlp/LuMXZQKzf77WfG7R65+Xuszfi04wOb9/6Bf6COAlzeSR44OFa7Pmv/X/rp9pTG94HrlDh77ieQgjc20MLw=
  template:
    metadata:
      name: terraria-password
      namespace: {{ .Values.namespace }}
