apiVersion: v1
kind: Service
metadata:
  name: terraria
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: terraria
      protocol: TCP
      name: terraria
  selector:
    app: terraria
