---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: subnet-router
  namespace: tailscale-system
spec:
  exitNode: true
  tags:
    - tag:k8s-operator
  subnetRouter:
    advertiseRoutes:
      - "10.244.0.0/16"
