---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: subnet-router
  namespace: tailscale-system
spec:
  exitNode: true
  tags:
    - tag:k8s-operator
  subnetRouter:
    advertiseRoutes:
      - "10.244.0.0/16"  # pod network
      - "10.96.0.0/12"   # service network (includes coredns custom at 10.104.27.74)
