{{- if .Values.connector.enabled }}
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: {{ .Values.connector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  exitNode: {{ .Values.connector.exitNode }}
  {{- with .Values.connector.tags }}
  tags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.connector.subnetRouter.enabled }}
  subnetRouter:
    advertiseRoutes:
      {{- range .Values.connector.subnetRouter.advertiseRoutes }}
      - {{ . | quote }}
      {{- end }}
  {{- end }}
{{- end }}
