{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: infisicalSecret
metadata:
  name: tailscale-oauth
  namespace: {{ .Release.Namespace }}
spec:
  hostAPI: {{ .Values.infisical.hostAPI }}
  resyncInterval: {{ .Values.infisical.resyncInterval }}

  authentication:
    universalAuth:
      credentialsref:
        secretName: {{ .Values.infisical.credentialsSecret.name }}
        secretNamespace: {{ .Values.infisical.credentialsSecret.namespace }}
      secretsScope:
        projectid: {{ .Values.infisical.projectId | quote }}
        envSlug: {{ .Values.infisical.envSlug }}
        secretsPath: {{ .Values.infisical.secretsPath | quote }}

  managedSecretReference:
    secretName: {{ .Values.tailscale-operator.oauth.secretName }}
    secretNamespace: {{ .Release.Namespace }}
{{- end }}
