---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgBHcEAcKTR0Prcn1TN4L6zUOhWn7YopZJJiUU/CzdUJkOiGY3KGwOfKbYWVtGEohxEe4e0ddmGC631Z722DiKyzHCsf6a1ZJS68Jz/r0fHqUxmjkODU9blU44jC7chWpmkaaOLhS7o0vsAHncr/6+Exepwx4kET9gTyi8xcAgvHD1VPkFYS8wXwrXriE2AUlMlqKdDKs1T64DUtgimeqN57XWSSz6LSOfx84NiBbk5EnecrdcO63QEtY5opbai8jBrZFpBGZMO6g5kS/bJF7c7DmVhsizoxM10U6dNYpRUmxenKe1cH2YhcblhesiAnCh/cYrpx4764BkNd+tfYV7QoGjOS6ONTNQV5QtlgYiTaViHHIjo3hQJaIXDLCoWp0xc+yVxhd3HYLBU38uuqi1i6Wj1Zl8FBmK7T806tzWmzGeiLLrdhG9HSSJeq9NvfBJIik4qD1xMH5oBbh+9o9A/reI/7orB8QOeeopFszjsHGdtBEY2FOhpnWDcrcg0lBhSMagDx+dfX/0cMnHKVj+Xp3mRVEcFSNJqn83joaq2KKt9YER0T1evxGD8VoORoF3pxPrLKaVU0fRrmxBhSbKTZoYagRXl2LW9s4pGPa6y+NOXWzmyrFgS4/YcyIFc9mR/0WidVJa+eaGT7JCVXwUyqC9NAOQ/VJutkJOR1nS7ke6dEJiDKtY7VwpNaTQkLP75TcuwAl8O77eriIruzuYNDMw==
    client_secret: AgAGeD58uXpmPB2MvFKC/sHmBWvJ9/wZx2ExavdWIQM9ZODWYM1VPlNEbGSNYfEPrNBEt1Lkd6LB/WCQ1jhmUaq/BCwJwrM/HC2Xga60mJlj4u16qlQse7jN63fQJkx7zyaSumksK0gpeTMXckmVMDjhVyv0Wm1TeBOmhsxL9/tmbB2wfwLQqXWBXFmS/s4tHf3JgMac98GHSZFvKXCjoc7+Y2POEVlYoDpWaMyrzeW5k9wrq0Ydhlm9QnEH9SNX8WyiuTEQ5imNZEnKlbUycrJcr6SiRzWzTRdd25Y27KtucsBgbLTxmCYFigANvhHf4P2HtZAgZqUeCk+gIoI6mdm8/UOttpmR0bjsDyWf9hm3F5O6yTzL9wwnF09NwCqAwcEX6Y44G9LmQEdEXxUJUp6bvefb7xnV1/jsNHwz7rVaY2wW+wDMlUI+v5qJUS2LJb5BUHTaoynTs0ftW6hrnPjmjW3jEznXQJLqEsavEB0iYxMIvPi2M9f2eN2mfn8i/KdE6DtIC5l0i86HwwqfQoNKraVbF5cyupA/l9GXg76zZMCOpHSTnl2OdNIEFNuyPLLdbdhWD8bWL2KTLDbfSPhHz6b8eUGYEu3WrWPm2sRzICRuN4u9ssY/jRHdyw8vy9MrRSqIgzHvAul05qQ6TBysvuXZK190OgJmybJZyFecx7w6sW1leq1hlmf+tJJaQ0+2SEITDEwZbM4o2U/cUS9Q/+JCZiNftlQp1o6v9hODOeFlZ86pcASlX1Hs9zwHp8zQKgexbxiEq6PHsj89uUM4
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
