---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgB8sOcC4oID3d51034XkW0Lde1Wl69pr8l9pDiOLCLuDH3aSQ7Qda+9QyK8CoR1qyZIXX1PecJ4pv3FaIVzrTsObgBgfcNyXVAAUrld8fT8VPGL/vU0ov8fL3zje0N0YWzyilJLcekkA5/z5bNM5nwroXLuuY5/8uaDuEc5/S9KHscisEzMJhOS9NPSLm+Cg7sdLegoyC39ZeAeKtWKgg9J9WpHc8WcYdovXUnvDbO5nAFKER6vJif/enpkHbbd/j2hNiOf0AOQii5JRBgLsiN80Yk7xZsWEO5licR1pmW0d9gXvAFZ2t6Cju39clLy3enxOhcTFCZgr+0H6aKtK8GU61+Sk73Q+DhIiwLmKe72lL48WmbCFxlocjtN1NQKkojj9K4KMqjeXD5hK3V/2iCKWdy4kV0mAcJDpJZEDJV3uSE44EsS3jLp3j2TwCaSV7lMa3uHC+qh2m1R23THGr38HxZGB7cFXMHJTGNaT/xyk6PYp5ATZ9D/IEnymOz2Xw4PWOMzqtmTqgTNdWQbFqVr68ETVuur6jMhMcSVAf8ZbE6pzJr964OAYayhzn1hEzgu5L6LcpU3+TLRrGrR1hTmou71bQKVdQVtpICckevS2RMK5CHyts/3q7yRCkJDKM3hLlMuuCcF16LuLQTggBYyUbruTjv8DvqwKr0Rd+yR+pCpPT22CwQmxH5MT8PqSuXiQrDRA1Y/t1VLRS4OP8A8KQ==
    client_secret: AgADy8LVcYsH5P3L/8MhlthGuxP4Z7QBGKiRjEJjvm7MrfPjfVHsbcs/u+1a02u7rluvU8QsNIf3S+homH7sl6WZDJCkkBvfdyx7s2toYmDSieaH7XN52drACy/5sTyhWUdvCjJ4DUqOb+uNzecOMqP8mGmpkZ0ClfOHa0YaujkHy9ejMqYSGM8cbYiqegCT3GtexIYEm74+CSGyRZFRrL41YG9FB4W8v4oW3LUoCzteC+oGTWOPvhKoxzuCvr168rdeo8SM+pg0yaHaEoaD61Y3WkvVubmuark6jcJ3NqJkkJWGTtbVfj1JDr1RSle0kdIlTryTr6V+8Rq9xoSNvW1HpzynayZLagQYwRqRVKh7DRmh9LdLUt7Nf+Y5uVLcqMwcvCoMD/9Q0jY3m1x6nqaqhZrMV4QVfSUfS7beZ1tQGAEzTKA8NY2N46YTocc36d4GJqwrI8ZtM90xAivLhVhqYnA+fXJ/YrdoAtoKPaEW+9AdpsXe/GyUaRFYRL1wXnOANQQzH784zp6vIumNA2Klig4O/MHvikAjjoFYNuVZu0vSlWi9KfKG1y/Cx1BG+EUGF2omLtKom1y2ry1+C+JCeID6BDWbkAPBXfgxjEx9m/O5QDgbUUNUucD0iK0RRUy4wZgd/UqIMbH6GhliinVTDpmakA9EpLlSL8+Tw6lki2EotJXs6TBXsGn/v+5So8Kkx9eOLa/pB8PrX8cqPmh2s1uc3VXUHFJPzWQtiIkl8Og7oXyM7MGhto3/eVRENifNPpWMdfAX4fgQuy+I4/5y
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
