---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgCA0+hO+v1Pd+vSAZNxJcD/2G3E6oC+RFcqKq8bAms2Itvpt+waJSWwgjfWHWX0vFbUXARAUj0w6mnipyyTRAvmO1uoyLjh85rFbeBFuWl3P5KN1m8sIPZ0YiScpImWxAVj68ZUMkgex0bQov9dQ7FiwohREdXU0mGrL0FBBbGSLxNL2z9MgmmPPJYBIs/KsxbDU6/5c0ges01Jn7KWmV5igdK/aGlyfFBigj4qNZoatZxTKPKoivQWTlhYPNWcvQQgB15ed91jNQd1NLVTW+Bbi6liVKrK0tXXbPDg5egkJ1SApZp2BHSACsWRy4e2J9IGGdnLKpPE6cp/ozdP9XEc4ca4dL+c9j/zd86ATsS4JQEKAo/u/HrvtPBfA41FLjBKJRH8GZXLRbue/h/PBG/wSpVNVjZnPVKeoBfz1yFZ1vpOg6c7aTuFaePJsG+L/CKeszh9FB4et4HWIbtemj1UosWOTPtD3+WQVPfvDJCKpsgdH3tNttj2OD10wN8IS+l/kx8SLUDBPrGWKEW5r3BW7vUEhQ4rejnQ4fgNbm5l6Wi0JtBZ/wnY6NZ6w39F1JQ7YH3Cl1qHmrvlgAukdWvMwvAiAL8NnF9YB3zevqNdG/W+NScUCejl5VjkQvX6LQL7rpxgFQdup5eDy7DQKfxkMSWUcx1QxGXWJM2IkkttMb9piUe5MXFYEAflGwl5KoiFVXIKUeQT6mD+S4piX1/FQw==
    client_secret: AgBN+CVsv2Dkqrk6F7LXvLupKbZnvdPDnDRkPRvElNC/xKaRoeFf70RSv5h72QYEs5MjR2Wa/psQOtNheTA93CbAGAyRMUVysFQRHaOryQhW9enXSBCpf2vsnYkkiHdSmIF7pDTG4OfrPxoKOOnXXfvc8jwZcscDKd1eX/QZ03UEVT5GRGDFSiGI9mM8QMCT7rjwfyDjB5uTjvv0fC5yp4LJMmdM/SF+BQvHRF83liYzXOqntFe+g2c10K1yuKnWqcMsTZ+gL031CRVRANkvhcP/Y+qpusKJNs7vC1FfVU2QCdb7A34ev4gx+HvsQtuTgweS1cL8udYRYK1d2HYS7RKXLnv9Kr00i8/iDtCVva1/CnHvW5FT4Tk9rKJaIM2myh9PjYoZ+dT3Jvh3vFg0qtDcfDvhhDmDSgO5K8n5AShicpw9HQnQwm5uSBPKT9AfvsWaVI7521cd3HV4Jw65Pwl4kTFjXcOsy2IJCFJ/cpS6TpFG8tIAN5Iq9wA3iEHX6PgupzoTULk1ME6xzDTY0R3qawphZ3vQlSqW1AzPJIY9ZpOtZThbNdqXL5tBV1GipYeMYu1f23fHPC0kmYbpI6rQ+dPLthvjgQETvQ2y04RjGbs+ScLdxduvDsSmNJa/AXHVPMg1Ykh7XL5aAvDhT8iccOmWbBUnzaWgAbapnvkutO2IIKpQU+fWiF28xyHdBE8EiKfzau9CBkKonUGmi4Kj8t9efY/hfS2druDxwtDPANYFpz/b+HbPKTSfLIrRJL2jTmQ0WRlfjw7UqDmpe8mS
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale-system
