apiVersion: v2
name: ts6-manager
description: TeamSpeak 6 web manager
type: application
version: 1.0.0
appVersion: "latest"
maintainers:
  - name: andrewzn69
dependencies:
  - name: common
    version: 1.0.5
    repository: oci://ghcr.io/andrewzn69
