apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaculikovolevevarle
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/andrewzn69/vaculikovolevevarle
      targetRevision: master
      path: chart
      helm:
        releaseName: vaculikovolevevarle
        values: |
          sealedSecrets:
            enabled: false
          persistence:
            lavalink:
              plugins:
                enabled: false
              logs:
                enabled: false
            bot:
              logs:
                enabled: false
    - repoURL: https://github.com/andrewzn69/kubernetes
      targetRevision: master
      path: apps/vaculikovolevevarle
  destination:
    server: https://kubernetes.default.svc
    namespace: vaculikovolevevarle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
