tailscale:
  hostname: vizima-internal-gateway

gateway:
  name: internal
  namespace: gateway-system
  gatewayClassName: cilium-internal
  controllerName: io.cilium/gateway-controller
  loadBalancerClass: tailscale
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        secretName: zemn-wildcard-tls
        secretNamespace: cert-manager
  allowedRoutes:
    namespaces: All
