tailscale:
  hostname: vizima-internal-gateway

gateway:
  name: internal
  namespace: gateway-system
  gatewayClassName: cilium-internal
  controllerName: io.cilium/gateway-controller
  loadBalancerClass: tailscale
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces: All
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        secretName: zemn-wildcard-tls
        secretNamespace: cert-manager
  allowedRoutes:
    namespaces: All

redirect:
  enabled: true
  hostnames:
    - "*.internal.zemn.xyz"
  statusCode: 301
