apiVersion: v2
name: plane
description: Open-source project management tool
type: application
version: 1.0.2
appVersion: 1.3.0
keywords:
  - plane
  - project-management
  - productivity
home: https://plane.so
maintainers:
  - name: andrewzn69
dependencies:
  - name: common
    version: 3.0.6
    repository: oci://ghcr.io/andrewzn69
