---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBlJhoQSfsRA6kCnxP7N3F351K5o0XlAn18YD4NHmknQmzzfPs4qx4S5KPSUsCZ+3GFRc6TFqvOckZWMiJWDfhSuRmnyRzN9v/aMJuK4+9V+VZXB/6MsmHu1Qk2NmhlDd/zRFL3UPdmut7OSSFx+YgLdIoFFocyUUHJv3RVRphmykNGe4GATMZieYRlH0ZzkmKFjvqsqqoAgAKbRZC7dDFwm8NSDIk070B/5dzTYTVl8wfYl8zu1q6RB8k5oPfsS8ztqYi2BwUV2tSwRxXfuMd9l67VRt/Fgow7vU2Qge7GVF5NdBxIaEhMjA+hEvPYzRiOS94Dm8Z9D25BAhTineiU99dTGrqg5qzZ10ha9hRI5u6dPMzK0qFvc2L55aEGwpJX3J2w0HYBE9wlvkLSoAOC5vTpZWgE9TeFTjs6VeiXFfTgZ+Y2Ef+3t9OxJ2tt1fwPcNCjpKBKVXB8qF5Y3exHTLHwmPlkS8w/MCsVpkLrvFE6gO+38KuYxrKbrT/OJw38+GcAibOAZuQVL4QuIg5wrTS9QnV7rsQH0usSw/knJ20tMwDzWdOStD7H6FjRgntVCioDINCflnmouPeFSwWOnZcpZ6PWxOUKggyxdiQHlsenRnxpgmmFrKuGdOR6o5YlzYimI8egvlG/3vln0yry1rtMBAS4seOupL4IlGB2i/H70VEYVaBe5d1THXpOstUmut08Jr/kyRpnSf4CMzNdt0D6s/gbHiIly6fKAWOPO1BkNSyjXjoE
  template:
    metadata:
      name: cert-manager-cloudflare-dns-token
      namespace: cert-manager
