{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cert-manager-cloudflare-token
  namespace: {{ .Release.Namespace }}
spec:
  hostAPI:
  resyncInterval: {{ .Values.infisical.resyncInterval }}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.infisical.credentialsSecret.name }}
        secretNamespace: {{ .Values.infisical.credentialsSecret.namespace }}
      secretsScope:
        projectId: {{ .Values.infisical.projectId | quote }}
        envSlug: {{ .Values.infisical.envSlug }}
        secretsPath: {{ .Values.infisical.secretsPath | quote }}
  managedSecretReference:
    secretName: {{ .Values.clusterIssuer.cloudflare.tokenSecretName }}
    secretNamespace: {{ .Release.Namespace }}
{{- end }}
