apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zemn-wildcard
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowd-namespaces: "media,productivity,default"
spec:
  secretName: zemn-wildcard-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
  - "zemn.xyz"
  - "*.zemn.xyz"
