apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teamspeak6
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andrewzn69/kubernetes
    targetRevision: HEAD
    path: charts/communication/teamspeak6
    helm:
      releaseName: teamspeak6
  destination:
    server: https://130.162.228.5:6443
    namespace: communication
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
