apiVersion: v2
name: infisical-operator
description: Infisical Kubernetes operator for secret management
type: application
version: 1.0.0
appVersion: "0.10.25"

dependencies:
  - name: secrets-operator
    version: 0.10.28
    repository: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
