longhorn:
  defaultSettings:
    defaultDataPath: /var/mnt/longhorn
    defaultReplicaCount: 2
    guaranteedInstanceManagerCPU: 5
    createDefaultDiskLabeledNodes: false
    storageMinimalAvailablePercentage: 10

  defaultBackupStore:
    backupTarget: ""
    backupTargetCredentialSecret: ""
    pollInterval: "0"

  persistence:
    defaultClass: true
    defaultClassReplicaCount: 2

  httproute:
    enabled: true
    parentRefs:
      - name: internal
        namespace: kube-system
    hostnames:
      - longhorn.internal.zemn.xyz
    path: /
    pathType: PathPrefix

  preUpgradeChecker:
    jobEnabled: false
