longhorn:
  defaultSettings:
    defaultDataPath: /var/mnt/longhorn
    defaultReplicaCount: 2
    guaranteedInstanceManagerCPU: 5
    createDefaultDiskLabeledNodes: false
    storageMinimalAvailablePercentage: 10

  defaultBackupStore:
    backupTarget: ""
    backupTargetCredentialSecret: ""
    pollInterval: "0"

  persistence:
    defaultClass: true
    defaultClassReplicaCount: 2

  ingress:
    enabled: false

  preUpgradeChecker:
    jobEnabled: false
