apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv
  labels:
    app: prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 100.64.100.64#/storage/apps/prometheus/data#prometheus-data
    volumeAttributes:
      server: "100.64.100.64"
      share: "/storage/apps/prometheus/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-pv
  labels:
    app: grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 100.64.100.64#/storage/apps/grafana/data#grafana-data
    volumeAttributes:
      server: "100.64.100.64"
      share: "/storage/apps/grafana/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-data-pv
  labels:
    app: alertmanager
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 100.64.100.64#/storage/apps/alertmanager/data#alertmanager-data
    volumeAttributes:
      server: "100.64.100.64"
      share: "/storage/apps/alertmanager/data"
