apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "minecraft.fullname" . }}-psp
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'hostpath'
    - 'emptyDir'
    - 'secret'
    - 'configMap'
  hostPath:
    pathPrefix: "/opt/minecraft-data"
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
