apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-operator-novigrad
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andrewzn69/kubernetes
    targetRevision: HEAD
    path: charts/infrastructure/infisical-operator
  destination:
    server: https://130.162.228.5:6443
    namespace: infisical-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
