apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andrewzn69/kubernetes
    targetRevision: HEAD
    path: charts/infrastructure/tailscale
    helm:
      releaseName: tailscale-operator
      values: |
        infisical:
          projectId: "481ebc3e-b9ed-40e7-9417-07aafe84aad1"
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
