namespace: media

image:
  repository: docker.io/linuxserver/sonarr
  tag: "4.0.15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8989
  targetPort: 8989
  protocol: TCP
  name: http

gateway:
  enabled: true
  gatewayName: internal
  gatewayNamespace: kube-system
  hostname: sonarr.internal.zemn.xyz
  path: /
  pathType: PathPrefix

volumes:
  pvc:
    - name: config
      mountPath: /config
      size: 5Gi
      readOnly: false
      accessMode: ReadWriteOnce
      storageClassName: longhorn

  nfs:
    - name: shows
      mountPath: /tv
      server: "100.64.100.64"
      path: "/storage/media/shows"
      readOnly: false
    - name: downloads
      mountPath: /downloads
      server: "100.64.100.64"
      path: "/storage/downloads"
      readOnly: false

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 500m

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: "Europe/Prague"

replicaCount: 1

configMap:
  enabled: false

initContainers:
  fixPermissions:
    enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

metrics:
  enabled: false

# exportarr:
#   enabled: true
#   type: sonarr
#   port: 9707
#   apiKeySecret: sonarr-api-key
#   image:
#     repository: ghcr.io/onedr0p/exportarr
#     tag: v2.0
#   additionalMetrics: true
