{{- range .Values.volumes.pvc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" $ }}-{{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ .accessMode }}
  storageClassName: {{ .storageClassName }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
