apiVersion: v2
name: argocd
description: Helm chart for ArgoCD and its cloudflared tunnel
type: application
version: 0.1.0
appVersion: v3.0.12
icon: https://raw.githubusercontent.com/argoproj/argo-cd/master/docs/assets/logo.png
dependencies:
  - name: argo-cd
    version: 8.2.5
    repository: https://argoproj.github.io/argo-helm
