argo-cd:
  global:
    domain: argocd.zemn.xyz
  server:
    insecure: false
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - argocd.zemn.xyz
      tls:
        - secretName: zemn-wildcard-tls
        - hosts:
            - argocd.zemn.xyz
