argo-cd:
  global:
    domain: argocd.zemn.xyz
  server:
    insecure: false
    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations:
        tailscale.com/funnel: "false"
        tailscale.com/tags: "tag:k8s-operator"
      hosts:
        - argocd.lab
      tls:
        - hosts:
            - argocd.lab
