argo-cd:
  global:
    domain: argocd.zemn.xyz
  server:
    insecure: false
    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations:
        tailscale.com/funnel: "false"
      hosts:
        - argocd.zemn.xyz
      tls:
        - hosts:
            - argocd.zemn.xyz
