apiVersion: v2
name: terraria
description: Helm chart dedicated Terraria server
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - terraria
  - gaming
maintainers:
  - name: andrewzn69
